build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - uses: actions/checkout@v2

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: application
              build-context: ./application #
